json.email user.email
json.first_name user.first_name
json.middle_name user.middle_name
json.last_name user.last_name
json.initials user.last_name
json.phone user.phone
json.employee_id user.employee_id
json.status user.status
json.avatar user.avatar
